app = "logs-shipper"

[metrics]
  port = 9598
  path = "/metrics"

[[services]]
  http_checks = []
  internal_port = 8686

[http_service]
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1